# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Josh Buchea
tagline:          Mobile & Web Developer
url:              http://joshbuchea.com
paginate:         5
baseurl:          http://joshbuchea.com/
author:
  name:           Josh Buchea
  url:            https://twitter.com/joshbuchea
  email:          josh@buchea.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
